AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  tvm-small-x86-amazon:2022

Globals:
  Function:
    Timeout: 30
    MemorySize: 4096

Resources:
  TvmSmallFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - arm64
      Events:
        ServerInfo:
          Type: Api
          Properties:
            Path: /tvmsmall
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./tvm_small
      DockerTag: tvmsmallamazon2022-v1

Outputs:
  TvmSmallApi:
    Description: "API Gateway endpoint URL for Prod stage for Tvm Small function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  TvmSmallFunction:
    Description: "Tvm Small Lambda Function ARN"
    Value: !GetAtt TvmSmallFunction.Arn
  TvmSmallFunctionIamRole:
    Description: "Implicit IAM Role created for Tvm Small function"
    Value: !GetAtt TvmSmallFunctionRole.Arn
