AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  tvm-small-x86-amazon:2022

Globals:
  Function:
    Timeout: 60
    MemorySize: 4096

Resources:
  TvmSmallFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      ImageConfig:
        Command: ["app.lambda_handler"]
      Events:
        ServerInfo:
          Type: HttpApi
          Properties:
            Path: /tvmsmall
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./tvm_small
      DockerTag: tvmsmallamazon2022-v1

  TvmSmallFunction2:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      ImageConfig:
        Command: ["app.lambda_handler2"]
      Events:
        ServerInfo:
          Type: HttpApi
          Properties:
            Path: /tvmsmall2
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./tvm_small
      DockerTag: tvmsmallamazon2022-v1
  
  TvmSmallFunction3:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      ImageConfig:
        Command: ["app.lambda_handler3"]
      Events:
        ServerInfo:
          Type: HttpApi
          Properties:
            Path: /tvmsmall3
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./tvm_small
      DockerTag: tvmsmallamazon2022-v1

  TvmSmallFunction4:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      Architectures:
        - x86_64
      ImageConfig:
        Command: ["app.lambda_handler4"]
      Events:
        ServerInfo:
          Type: HttpApi
          Properties:
            Path: /tvmsmall4
            Method: post
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./tvm_small
      DockerTag: tvmsmallamazon2022-v1

Outputs:
  TvmSmallApi:
    Description: "API Gateway endpoint URL for Prod stage for Tvm Small function"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  TvmSmallFunction:
    Description: "Tvm Small Lambda Function ARN"
    Value: !GetAtt TvmSmallFunction.Arn
  TvmSmallFunctionIamRole:
    Description: "Implicit IAM Role created for Tvm Small function"
    Value: !GetAtt TvmSmallFunctionRole.Arn
